### PR TITLE
2.4.1

### PR DESCRIPTION
**Pull request by thomasriley**
## Pull Request Checklist

sensu-plugins/sensu-plugins-feature-requests#27

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose
Add testing for Ruby 2.4.1
Remove redundant Ruby pre-2.0 code

### CODE REVIEW

**Comment by majormoses** [comment]
looks like we need to restrict the dependency for json per: https://travis-ci.org/sensu-plugins/sensu-plugins-github/jobs/252171273#L302

**Comment by majormoses** [comment]
I will take a look tonight when I have some time. Thanks again for doing this.

**Comment by thomasriley** [comment]
@majormoses been racking my brains on this json issue but getting late over here, will have another glance tomorrow if you don't get a chance to look it over. Intrigued what the issue could be!

**Comment by majormoses** [comment]
Oh I know the issue, just how to solve it is what I am unsure about. basically we have an unbounded json dependency  so it is pulling in latest. 2 different versions are conflicting so we will need to update one of them to pin above or below the affected version.

**Comment by majormoses** [comment]
so this is one of those scenarios where a breaking change is the only way forward, we are gonna have to bump our deps to sensu-plugin 2.x in order to move forward...I know I had to do the same with at least 1 other gem.

**Comment by majormoses** [comment]
I bumped the following dep (breaking change now) like this that solves it:
```
$ git diff
diff --git a/sensu-plugins-github.gemspec b/sensu-plugins-github.gemspec
index 2d75733..096d171 100644
--- a/sensu-plugins-github.gemspec
+++ b/sensu-plugins-github.gemspec
@@ -39,7 +39,7 @@ Gem::Specification.new do |s|
   s.version                = SensuPluginsGithub::Version::VER_STRING
 
   s.add_runtime_dependency 'rest-client',  '1.8.0'
-  s.add_runtime_dependency 'sensu-plugin', '~> 1.2'
+  s.add_runtime_dependency 'sensu-plugin', '~> 2.0'
 
   s.add_development_dependency 'bundler',                   '~> 1.7'
   s.add_development_dependency 'codeclimate-test-reporter', '~> 0.4'
```

This should be added to the changelog in a `### Breaking Changes` header just you did previously with Added.

**Pull request merged**
